slam_toolbox:
  ros__parameters:
    # Solver parameters
    solver_plugin: solver_plugins::AztecSolver
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_sim_time: false # WAJIB FALSE untuk robot asli

    # Mapping Parameters
    mode: mapping
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000